# Generated by Django 3.1.2 on 2020-11-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='a_name', max_length=255)),
                ('online', models.BooleanField(db_column='a_online')),
            ],
            options={
                'db_table': 't_shops',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_column='a_month', max_length=5)),
                ('budget_amount', models.DecimalField(db_column='a_budget_amount', decimal_places=2, max_digits=10)),
                ('amount_spent', models.DecimalField(db_column='a_amount_spent', decimal_places=2, max_digits=10)),
                ('shop_id', models.ForeignKey(db_column='a_shop_id', on_delete=django.db.models.deletion.CASCADE, to='budget_notify.shop')),
            ],
            options={
                'db_table': 't_budgets',
            },
        ),
    ]
